name: Test
on:
  pull_request:
  push:
    branches:
    - master
    tags:
    - v*
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v1
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build
      run: go build ./...
    - name: Test
      run: go test ./...
    - name: Lint
      uses: golangci/golangci-lint-action@v2
      with:
        version: v1.42.1
